// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['pkg']['App']['AddTask'](arg1, arg2);
}

export function ApproveTask(arg1) {
  return window['go']['pkg']['App']['ApproveTask'](arg1);
}

export function ConnectDB(arg1) {
  return window['go']['pkg']['App']['ConnectDB'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['pkg']['App']['DeleteTask'](arg1);
}

export function GetActiveCount() {
  return window['go']['pkg']['App']['GetActiveCount']();
}

export function GetChatMessages(arg1) {
  return window['go']['pkg']['App']['GetChatMessages'](arg1);
}

export function GetDBStatus() {
  return window['go']['pkg']['App']['GetDBStatus']();
}

export function GetDesignDoc() {
  return window['go']['pkg']['App']['GetDesignDoc']();
}

export function GetDesignHistory() {
  return window['go']['pkg']['App']['GetDesignHistory']();
}

export function GetSettings() {
  return window['go']['pkg']['App']['GetSettings']();
}

export function GetWorkDir() {
  return window['go']['pkg']['App']['GetWorkDir']();
}

export function LoadTasks() {
  return window['go']['pkg']['App']['LoadTasks']();
}

export function PickDirectory() {
  return window['go']['pkg']['App']['PickDirectory']();
}

export function SaveSettings(arg1) {
  return window['go']['pkg']['App']['SaveSettings'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['pkg']['App']['SendChatMessage'](arg1, arg2);
}

export function SetWorkDir(arg1) {
  return window['go']['pkg']['App']['SetWorkDir'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['pkg']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
