// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['pkg']['App']['AddTask'](arg1, arg2);
}

export function ApproveTask(arg1) {
  return window['go']['pkg']['App']['ApproveTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['pkg']['App']['DeleteTask'](arg1);
}

export function GetWorkDir() {
  return window['go']['pkg']['App']['GetWorkDir']();
}

export function LoadTasks() {
  return window['go']['pkg']['App']['LoadTasks']();
}

export function SetWorkDir() {
  return window['go']['pkg']['App']['SetWorkDir']();
}
