// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['main']['App']['AddTask'](arg1, arg2);
}

export function ApproveTask(arg1) {
  return window['go']['main']['App']['ApproveTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}
