// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function AddTask(arg1:string,arg2:string):Promise<void>;

export function ApproveTask(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetActiveCount():Promise<number>;

export function GetDesignDoc():Promise<string>;

export function GetDesignHistory():Promise<Array<pkg.DesignVersion>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetWorkDir():Promise<string>;

export function LoadTasks():Promise<Array<pkg.Task>>;

export function PickDirectory():Promise<string>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SetWorkDir(arg1:string):Promise<void>;
