// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:string):Promise<void>;

export function ApproveTask(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetWorkDir():Promise<string>;

export function LoadTasks():Promise<Array<main.Task>>;

export function SetWorkDir():Promise<string>;
